spec-version: 0.34.7

name: bakery-shell
synopsis: Cakes, not baking.
author:
  - Samir Talwar <samir@noodlesandwich.com>

github: SamirTalwar/bakery

default-extensions:
  - BlockArguments
  - DeriveFunctor
  - DerivingStrategies
  - ExplicitForAll
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - StandaloneDeriving
  - TypeOperators
  - TypeSynonymInstances

ghc-options:
  - -Wall
  - -Werror

dependencies:
  - base
  - bakery-core
  - bytestring
  - pipes
  - pipes-bytestring
  - pipes-safe
  - typed-process

library:
  source-dirs:
    - src

tests:
  bakery-shell-test:
    main: Main.hs
    source-dirs:
      - test
    dependencies:
      - base
      - hspec

      - bakery-shell
