spec-version: 0.34.7

name: bakery-core
synopsis: Cakes, not baking.
author:
  - Samir Talwar <samir@noodlesandwich.com>

github: SamirTalwar/bakery

default-extensions:
  - DeriveFunctor
  - DerivingStrategies
  - ExplicitForAll
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - NamedFieldPuns
  - StandaloneDeriving

ghc-options:
  - -Wall
  - -Werror

dependencies:
  - base
  - transformers

library:
  source-dirs:
    - src
