spec-version: 0.34.7

name: bakery-examples
synopsis: Exmples of cakes.
author:
  - Samir Talwar <samir@noodlesandwich.com>

github: SamirTalwar/bakery

default-extensions:
  - BlockArguments
  - ExtendedDefaultRules
  - ImportQualifiedPost

dependencies:
  - base
  - bakery

executables:
  example-echo:
    main: bake.hs
    source-dirs:
      - echo
  example-exec:
    main: bake.hs
    source-dirs:
      - exec
  example-files:
    main: bake.hs
    source-dirs:
      - files
  example-uppercase:
    main: bake.hs
    source-dirs:
      - uppercase
